# DEV
version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/opt/cthulhu-text/dev/
    environment:
      debug: ${DEBUG:-true}
      SPRING_PROFILES_ACTIVE: dev