version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      debug: ${DEBUG:-false}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"