application:
  name: '@project.artifactId@'
  build:
    version: '@project.version@'
spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
